version: 0.9.{build}

os: Visual Studio 2015

configuration: Release
platform: Any CPU

environment:
  solution_path: src\SonarLint.VisualStudio.Integration.sln

before_build:
  - cmd: nuget restore $(solution_path)

build:
  verbosity: minimal
  project: $(solution_path)

on_finish:
# uncomment to enable RDP to the build agent
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
